# Generated by Django 5.0.4 on 2024-05-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_listened'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='count_songs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
