# Generated by Django 5.0.4 on 2024-05-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_artist_number_albums'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['id']},
        ),
    ]
