# Generated by Django 5.0.4 on 2024-05-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_song_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['id']},
        ),
    ]
