# Generated by Django 5.0.4 on 2024-04-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_comment_customer_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
